/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class one_papachi_tuntap4j_NetworkDevice */

#ifndef _Included_one_papachi_tuntap4j_NetworkDevice
#define _Included_one_papachi_tuntap4j_NetworkDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    isOpen
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_one_papachi_tuntap4j_NetworkDevice_isOpen
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    open
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_one_papachi_tuntap4j_NetworkDevice_open
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    read
 * Signature: (Ljava/lang/String;JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_one_papachi_tuntap4j_NetworkDevice_read
  (JNIEnv *, jclass, jstring, jlong, jobject);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    write
 * Signature: (Ljava/lang/String;JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_one_papachi_tuntap4j_NetworkDevice_write
  (JNIEnv *, jclass, jstring, jlong, jobject);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    close
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_one_papachi_tuntap4j_NetworkDevice_close
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    setStatus
 * Signature: (Ljava/lang/String;JZ)V
 */
JNIEXPORT void JNICALL Java_one_papachi_tuntap4j_NetworkDevice_setStatus
  (JNIEnv *, jclass, jstring, jlong, jboolean);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    getIPAddress
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_one_papachi_tuntap4j_NetworkDevice_getIPAddress
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    setIPAddress
 * Signature: (Ljava/lang/String;JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_one_papachi_tuntap4j_NetworkDevice_setIPAddress
  (JNIEnv *, jclass, jstring, jlong, jstring, jstring);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    getMTU
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_one_papachi_tuntap4j_NetworkDevice_getMTU
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    setMTU
 * Signature: (Ljava/lang/String;JI)V
 */
JNIEXPORT void JNICALL Java_one_papachi_tuntap4j_NetworkDevice_setMTU
  (JNIEnv *, jclass, jstring, jlong, jint);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    getMACAddress
 * Signature: (Ljava/lang/String;J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_one_papachi_tuntap4j_NetworkDevice_getMACAddress
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     one_papachi_tuntap4j_NetworkDevice
 * Method:    setMACAddress
 * Signature: (Ljava/lang/String;J[B)V
 */
JNIEXPORT void JNICALL Java_one_papachi_tuntap4j_NetworkDevice_setMACAddress
  (JNIEnv *, jclass, jstring, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
